version: '2.0'
services:
  registry:
    image: registry:latest
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./registry-data:/var/lib/registry
    networks:
      - registry-ui-net

  ui:
    image: joxit/docker-registry-ui:latest
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=My Private Docker Registry
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./nginx/privkey.pem:/etc/nginx/certs/privkey.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - registry
